### ISSUE TITLE
Handle disk full due to metadata

### ISSUE THREAD

**Issue by wmertens** [GrahamCobb/btrfs-balance-slowly#1]
Btrfs can go haywire when the disk is full or near full, because metadata is unbalanced and there's no place to put new blocks.

I found that the only way to fix this is to make sure there is at least some place, and then repeatedly run balance with -dusage=n or -musage=n with ever increasing `n` until at least one block is rebalanced.

I wonder if the python script could do something similar?

**Comment by GrahamCobb** [comment]
Yes. The script sorts the block groups by usage, and starts with the one which is least used. Using limits you can tell the script to stop after one block group has been balanced.

So, the command to do what you are looking for would be:

`btrfs-balance-slowly.python --limit 1 --portion-limit 1 -d -m <mountpoint>`

**Comment by wmertens** [comment]
Excellent, thanks!
